from .Cover import Cover
from .TableOfContents import TableOfContents
from .ExecutiveSummary import ExecutiveSummary
from .BusinessGoals import BusinessGoals
from .ConsolidationApproach import ConsolidationApproach
from .CalculationMethod import CalculationMethod
from .ScopeBreakdown import ScopeBreakdown
from .SupplierBreakdown import SupplierBreakdown
from .Scope3 import Scope3
from .Scope2 import Scope2
from .Scope1 import Scope1
